// <auto-generated />
using DAL.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(WarehouseContext))]
    [Migration("20210521141246_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("DAL.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Juice",
                            Description = "Description how to store juice..."
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Water",
                            Description = "Description how to store water..."
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Soda",
                            Description = "Description how to store soda..."
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Beer",
                            Description = "Description how to store beer..."
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Wine",
                            Description = "Description how to store wine..."
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Whiskey",
                            Description = "Description how to store whiskey..."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
